// Copyright GraphCaster. All Rights Reserved.

import type { TemplateMeta } from "./templates";

export const LOCAL_TEMPLATES: TemplateMeta[] = [
  {
    id: "ai-summarize-docs",
    name: "Summarize documents with AI",
    description: "Loads documents, splits them into chunks and produces a concise summary with an LLM.",
    author: { name: "GraphCaster Team" },
    categories: ["AI"],
    nodes: ["http.request", "ai.llm", "text.split", "set"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-01-15T10:00:00Z",
    views: 12480,
    tags: ["llm", "summarize"],
  },
  {
    id: "ai-customer-support",
    name: "AI customer support assistant",
    description: "Reads incoming tickets, classifies them with an LLM and routes to the right team.",
    author: { name: "GraphCaster Team" },
    categories: ["AI", "Communication"],
    nodes: ["webhook", "ai.llm", "switch", "slack.message"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-02-02T09:30:00Z",
    views: 8420,
    tags: ["llm", "support"],
  },
  {
    id: "marketing-newsletter",
    name: "Weekly newsletter sender",
    description: "Pulls fresh blog posts, formats them and sends a weekly email digest.",
    author: { name: "Marketing Crew" },
    categories: ["Marketing", "Communication"],
    nodes: ["cron", "http.request", "email.send"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-01-22T08:00:00Z",
    views: 5610,
    tags: ["email", "newsletter"],
  },
  {
    id: "marketing-lead-enrichment",
    name: "Lead enrichment pipeline",
    description: "Enriches inbound leads with company data and syncs them to the CRM.",
    author: { name: "Marketing Crew" },
    categories: ["Marketing", "Data"],
    nodes: ["webhook", "http.request", "set", "hubspot.contact"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-02-18T14:20:00Z",
    views: 3320,
    tags: ["leads", "crm"],
  },
  {
    id: "itops-monitor-uptime",
    name: "Endpoint uptime monitor",
    description: "Pings a list of endpoints on a schedule and alerts on failures.",
    author: { name: "IT Ops" },
    categories: ["IT Ops"],
    nodes: ["cron", "http.request", "if", "slack.message"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-01-05T07:45:00Z",
    views: 7980,
    tags: ["monitoring", "alerts"],
  },
  {
    id: "itops-backup-rotation",
    name: "Database backup rotation",
    description: "Runs daily database backups and rotates older snapshots from object storage.",
    author: { name: "IT Ops" },
    categories: ["IT Ops", "Data"],
    nodes: ["cron", "postgres", "s3.upload", "s3.delete"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-03-01T03:00:00Z",
    views: 2210,
    tags: ["backup", "ops"],
  },
  {
    id: "devops-ci-failure-triage",
    name: "CI failure triage",
    description: "Catches failing CI builds, asks an LLM for a summary and posts to chat.",
    author: { name: "DevOps Guild" },
    categories: ["DevOps", "AI"],
    nodes: ["webhook", "ai.llm", "slack.message"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-02-28T11:10:00Z",
    views: 4760,
    tags: ["ci", "github"],
  },
  {
    id: "devops-release-notes",
    name: "Auto release notes",
    description: "Collects merged pull requests and generates release notes for the next tag.",
    author: { name: "DevOps Guild" },
    categories: ["DevOps"],
    nodes: ["webhook", "github.list", "ai.llm", "github.release"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-03-10T16:00:00Z",
    views: 3140,
    tags: ["release", "github"],
  },
  {
    id: "data-csv-to-warehouse",
    name: "CSV to data warehouse",
    description: "Watches an inbox for CSV files and loads them into the data warehouse.",
    author: { name: "Data Team" },
    categories: ["Data"],
    nodes: ["imap", "csv.parse", "bigquery.insert"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-02-14T12:00:00Z",
    views: 2680,
    tags: ["etl", "csv"],
  },
  {
    id: "data-daily-metrics",
    name: "Daily metrics report",
    description: "Aggregates daily product metrics and posts a summary to the team channel.",
    author: { name: "Data Team" },
    categories: ["Data", "Communication"],
    nodes: ["cron", "postgres", "set", "slack.message"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-03-22T06:00:00Z",
    views: 5990,
    tags: ["metrics", "report"],
  },
  {
    id: "comm-slack-digest",
    name: "Slack channel digest",
    description: "Summarizes unread messages from selected Slack channels into one digest.",
    author: { name: "Productivity Lab" },
    categories: ["Communication", "AI"],
    nodes: ["cron", "slack.history", "ai.llm", "email.send"],
    workflow: { nodes: [], edges: [] },
    createdAt: "2026-03-05T18:30:00Z",
    views: 4120,
    tags: ["slack", "digest"],
  },
];
