@REM Copyright Aura. All Rights Reserved.
@echo off
setlocal EnableDelayedExpansion

set "MONITOR_DIR=%~dp0"
set "MONITOR_PROJ=%MONITOR_DIR%AgentQueueMonitor.csproj"
set "OUT=%MONITOR_DIR%CLI_SETUP.generated.txt"
set "MONITOR_EXE=%MONITOR_DIR%bin\Release\net8.0-windows\AgentQueueMonitor.exe"
set "MONITOR_LNK=%MONITOR_DIR%Agent Queue Monitor.lnk"

pushd "%MONITOR_DIR%.." || exit /b 1
set "AQ_DIR=%CD%"
popd

for /f "delims=" %%R in ('powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%MONITOR_DIR%resolve-repo-root-for-shortcut.ps1" "%AQ_DIR%"') do set "REPO_ROOT=%%R"

where pwsh >nul 2>&1
if errorlevel 1 (
    set "PS_EXE=powershell"
) else (
    set "PS_EXE=pwsh"
)

echo.
echo === Agent Queue Monitor: Cursor CLI + build ===
echo Cursor workspace / shortcut start-in: %REPO_ROOT%
echo Monitor / CLI setup file dir: %MONITOR_DIR%
echo.

set "DOTNET_ERR_MSG=[ERROR] dotnet not found. Install .NET 8 SDK: https://dotnet.microsoft.com/download/dotnet/8.0"
where dotnet >nul 2>&1
if errorlevel 1 (
    echo !DOTNET_ERR_MSG!
    exit /b 1
)

for /f "delims=" %%v in ('dotnet --version 2^>nul') do set "DOTNET_VER=%%v"
echo Found dotnet SDK: !DOTNET_VER!

echo PowerShell: !PS_EXE!

set "CA=%LOCALAPPDATA%\cursor-agent"
set "CLI_OK=0"
where agent >nul 2>&1
if not errorlevel 1 set "CLI_OK=1"
if "%CLI_OK%"=="0" (
    where cursor-agent >nul 2>&1
    if not errorlevel 1 set "CLI_OK=1"
)
if "%CLI_OK%"=="0" (
    if exist "%CA%\agent.cmd" set "CLI_OK=1"
)

set "INSTALL_RAN=skipped"
echo.
if "%CLI_OK%"=="1" (
    echo [1/3] Cursor CLI already on PATH ^(agent, cursor-agent, or "%CA%\agent.cmd"^) - install skipped.
    if exist "%CA%\agent.cmd" set "PATH=%CA%;%PATH%"
) else (
    echo [1/3] Installing Cursor CLI ^(official script from cursor.com^)...
    echo       Follow the installer prompts if asked.
    echo.
    set "INSTALL_RAN=performed"
    "%PS_EXE%" -NoProfile -ExecutionPolicy Bypass -File "%MONITOR_DIR%build-monitor-install-cursor.ps1"
    if errorlevel 1 (
        echo [ERROR] Cursor CLI install failed.
        exit /b 1
    )
    if exist "%CA%\agent.cmd" set "PATH=%CA%;%PATH%"
)

echo.
echo [2/3] Writing CLI info and checks...
set "TS=%DATE% %TIME%"
(
    echo # Generated by monitor/build-monitor.bat - do not commit ^(see .gitignore^)
    echo # Date: !TS!
    echo CURSOR_WORKSPACE_DEFAULT=%REPO_ROOT%
    echo MONITOR_DIR=%MONITOR_DIR%
    echo AGENT_QUEUE_DIR=!AQ_DIR!
    echo DOTNET_SDK=!DOTNET_VER!
    echo LOCALAPPDATA_CURSOR_AGENT=%CA%
    echo CURSOR_CLI_INSTALL=!INSTALL_RAN!
    echo.
    echo ## agent check
    echo.
) > "%OUT%"

where agent >> "%OUT%" 2>&1
if exist "%CA%\agent.cmd" (
    echo. >> "%OUT%"
    echo agent.cmd --version: >> "%OUT%"
    call "%CA%\agent.cmd" --version >> "%OUT%" 2>&1
)

echo Wrote: %OUT%

echo.
echo [3/3] Building Agent Queue Monitor ^(Release^)...
dotnet build -c Release "%MONITOR_PROJ%"
set "BUILD_EXIT=%ERRORLEVEL%"
(
    echo.
    echo ## monitor build
    echo dotnet build -c Release %MONITOR_PROJ%
    echo exit code: %BUILD_EXIT%
) >> "%OUT%"

if not "%BUILD_EXIT%"=="0" (
    echo [ERROR] Build failed.
    exit /b 1
)

if not exist "%MONITOR_EXE%" goto :NoMonitorExe

"%PS_EXE%" -NoProfile -ExecutionPolicy Bypass -File "%MONITOR_DIR%build-monitor-create-shortcut.ps1" -ExePath "%MONITOR_EXE%" -ShortcutPath "%MONITOR_LNK%" -WorkingDirectory "%REPO_ROOT%"
if errorlevel 1 (
    echo [WARN] Could not create shortcut.
    goto :AfterMonitorShortcut
)
echo Shortcut: "%MONITOR_LNK%"
(
    echo.
    echo ## shortcut
    echo %MONITOR_LNK%
) >> "%OUT%"
goto :AfterMonitorShortcut

:NoMonitorExe
echo [WARN] Not found: %MONITOR_EXE% - shortcut skipped.

:AfterMonitorShortcut

echo.
echo Done. Monitor exe: %MONITOR_EXE%
echo New terminal may not see PATH for agent - reopen session or add to PATH: %%LOCALAPPDATA%%\cursor-agent
echo.
exit /b 0
