// Copyright GraphCaster. All Rights Reserved.

import {
  AlignRight,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightFromLine,
  ArrowRightToLine,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  Book,
  BookOpen,
  Bot,
  Box,
  Braces,
  Brain,
  Bug,
  Building2,
  Calculator,
  Calendar,
  CaseUpper,
  ChartColumnDecreasing,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsUpDown,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleEllipsis,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleUserRound,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  Code,
  Cog,
  Columns3 as Columns3Cog,
  Contrast,
  Copy,
  Crosshair,
  Database,
  DoorOpen,
  Dot,
  Download,
  Earth,
  Ellipsis,
  EllipsisVertical,
  Equal,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileDiff,
  FileDown,
  FileInput,
  FileOutput,
  FileText,
  Files,
  Fingerprint,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderPlus,
  Filter as Funnel,
  Gem,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Grid2x2,
  GripVertical,
  HandCoins,
  Handshake,
  HardDrive,
  HardDriveDownload,
  Hash,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Languages,
  Layers,
  LayoutTemplate,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquarePlus,
  MessagesSquare,
  Mic,
  Milestone,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MousePointer,
  Network,
  NotebookPen,
  PackageOpen,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pause,
  Pen,
  Pencil,
  PencilOff,
  Pin,
  Play,
  Plug,
  Plus,
  PocketKnife,
  Power,
  Redo2,
  RefreshCw,
  RemoveFormatting,
  Rss,
  SatelliteDish,
  Save,
  Scale,
  Scissors,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share,
  Shield,
  ShieldHalf,
  Shield as ShieldUser,
  Scissors as Shredder,
  SkipForward,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Split,
  Square,
  SquareCheck,
  SquareMinus,
  SquarePen,
  SquarePlus,
  Star,
  StickyNote,
  Sun,
  Table,
  Tags,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleRight,
  Trash2,
  TreePine,
  TriangleAlert,
  Type,
  Undo2,
  Unlink,
  Upload,
  User,
  UserCheck,
  Lock as UserLock,
  UserPen,
  UserRound,
  Users,
  Variable,
  Vault,
  Video,
  Volume2,
  VolumeX,
  WandSparkles,
  Waypoints,
  Workflow,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

import AnthropicSvg from "./custom/anthropic.svg?react";
import BinarySvg from "./custom/binary.svg?react";
import BoltFilledSvg from "./custom/bolt-filled.svg?react";
import ContinueSvg from "./custom/continue.svg?react";
import EmptyOutputSvg from "./custom/empty-output.svg?react";
import FilledSquareSvg from "./custom/filled-square.svg?react";
import FormSvg from "./custom/form.svg?react";
import GripLinesVerticalSvg from "./custom/grip-lines-vertical.svg?react";
import LovableSvg from "./custom/lovable.svg?react";
import McpSvg from "./custom/mcp.svg?react";
import NodeDirtySvg from "./custom/node-dirty.svg?react";
import NodeEllipsisSvg from "./custom/node-ellipsis.svg?react";
import NodeExecutionErrorSvg from "./custom/node-execution-error.svg?react";
import NodePinSvg from "./custom/node-pin.svg?react";
import NodePlaySvg from "./custom/node-play.svg?react";
import NodePowerSvg from "./custom/node-power.svg?react";
import NodeSuccessSvg from "./custom/node-success.svg?react";
import NodeTrashSvg from "./custom/node-trash.svg?react";
import NodeValidationErrorSvg from "./custom/node-validation-error.svg?react";
import PopOutSvg from "./custom/pop-out.svg?react";
import ResolverSvg from "./custom/resolver.svg?react";
import RetrySvg from "./custom/retry.svg?react";
import RunOnceSvg from "./custom/run-once.svg?react";
import SchemaSvg from "./custom/schema.svg?react";
import SpinnerSvg from "./custom/spinner.svg?react";
import StatusCanceledSvg from "./custom/status-canceled.svg?react";
import StatusCompletedSvg from "./custom/status-completed.svg?react";
import StatusErrorSvg from "./custom/status-error.svg?react";
import StatusNewSvg from "./custom/status-new.svg?react";
import StatusUnknownSvg from "./custom/status-unknown.svg?react";
import StatusWaitingSvg from "./custom/status-waiting.svg?react";
import StatusWarningSvg from "./custom/status-warning.svg?react";
import TextSvg from "./custom/text.svg?react";
import ToolboxSvg from "./custom/toolbox.svg?react";
import TriangleSvg from "./custom/triangle.svg?react";
import VectorSquareSvg from "./custom/vector-square.svg?react";
import WebhookSvg from "./custom/webhook.svg?react";

export const ICON_REGISTRY = {
  // Custom SVG icons
  anthropic: AnthropicSvg,
  binary: BinarySvg,
  "bolt-filled": BoltFilledSvg,
  "continue-on-error": ContinueSvg,
  "always-output-data": EmptyOutputSvg,
  "filled-square": FilledSquareSvg,
  form: FormSvg,
  "grip-lines-vertical": GripLinesVerticalSvg,
  lovable: LovableSvg,
  mcp: McpSvg,
  "node-dirty": NodeDirtySvg,
  "node-ellipsis": NodeEllipsisSvg,
  "node-execution-error": NodeExecutionErrorSvg,
  "node-pin": NodePinSvg,
  "node-play": NodePlaySvg,
  "node-power": NodePowerSvg,
  "node-success": NodeSuccessSvg,
  "node-trash": NodeTrashSvg,
  "node-validation-error": NodeValidationErrorSvg,
  "pop-out": PopOutSvg,
  resolver: ResolverSvg,
  "retry-on-fail": RetrySvg,
  "execute-once": RunOnceSvg,
  schema: SchemaSvg,
  spinner: SpinnerSvg,
  "status-canceled": StatusCanceledSvg,
  "status-completed": StatusCompletedSvg,
  "status-error": StatusErrorSvg,
  "status-new": StatusNewSvg,
  "status-unknown": StatusUnknownSvg,
  "status-waiting": StatusWaitingSvg,
  "status-warning": StatusWarningSvg,
  text: TextSvg,
  toolbox: ToolboxSvg,
  triangle: TriangleSvg,
  "vector-square": VectorSquareSvg,
  webhook: WebhookSvg,

  // Lucide icons (kebab-case keys)
  "align-right": AlignRight,
  archive: Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-right-from-line": ArrowRightFromLine,
  "arrow-right-to-line": ArrowRightToLine,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  "badge-check": BadgeCheck,
  ban: Ban,
  bell: Bell,
  book: Book,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  braces: Braces,
  brain: Brain,
  bug: Bug,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  "case-upper": CaseUpper,
  "chart-column-decreasing": ChartColumnDecreasing,
  check: Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-ellipsis": CircleEllipsis,
  "more-horizontal": Ellipsis,
  "more-vertical": EllipsisVertical,
  "circle-help": CircleHelp,
  "circle-minus": CircleMinus,
  "circle-pause": CirclePause,
  "circle-play": CirclePlay,
  "circle-plus": CirclePlus,
  "circle-user-round": CircleUserRound,
  "circle-x": CircleX,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cloud: Cloud,
  "cloud-download": CloudDownload,
  code: Code,
  "code-2": Code,
  key: Code,
  cog: Cog,
  "columns-3-cog": Columns3Cog,
  contrast: Contrast,
  copy: Copy,
  crosshair: Crosshair,
  database: Database,
  "door-open": DoorOpen,
  dot: Dot,
  download: Download,
  earth: Earth,
  ellipsis: Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  equal: Equal,
  expand: Expand,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-archive": FileArchive,
  "file-code": FileCode,
  "file-diff": FileDiff,
  "file-down": FileDown,
  "file-input": FileInput,
  "file-output": FileOutput,
  "file-text": FileText,
  files: Files,
  fingerprint: Fingerprint,
  "flask-conical": FlaskConical,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  funnel: Funnel,
  gem: Gem,
  gift: Gift,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "grid-2x2": Grid2x2,
  "grip-vertical": GripVertical,
  "hand-coins": HandCoins,
  handshake: Handshake,
  "hard-drive": HardDrive,
  "hard-drive-download": HardDriveDownload,
  hash: Hash,
  history: History,
  hourglass: Hourglass,
  house: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  languages: Languages,
  layers: Layers,
  "layout-template": LayoutTemplate,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  "list-checks": ListChecks,
  loader: Loader2,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  maximize: Maximize,
  "maximize-2": Maximize2,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "message-square-plus": MessageSquarePlus,
  "messages-square": MessagesSquare,
  mic: Mic,
  milestone: Milestone,
  "minimize-2": Minimize2,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "mouse-pointer": MousePointer,
  network: Network,
  "notebook-pen": NotebookPen,
  "package-open": PackageOpen,
  palette: Palette,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  paperclip: Paperclip,
  pause: Pause,
  pen: Pen,
  pencil: Pencil,
  "pencil-off": PencilOff,
  pin: Pin,
  play: Play,
  plug: Plug,
  plus: Plus,
  "pocket-knife": PocketKnife,
  power: Power,
  "redo-2": Redo2,
  "refresh-cw": RefreshCw,
  "remove-formatting": RemoveFormatting,
  robot: Bot,
  rss: Rss,
  "satellite-dish": SatelliteDish,
  save: Save,
  scale: Scale,
  scissors: Scissors,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  settings2: Settings2,
  share: Share,
  shield: Shield,
  "shield-half": ShieldHalf,
  "shield-user": ShieldUser,
  shredder: Shredder,
  "skip-forward": SkipForward,
  "sliders-horizontal": SlidersHorizontal,
  smile: Smile,
  sparkles: Sparkles,
  split: Split,
  square: Square,
  "square-check": SquareCheck,
  "square-minus": SquareMinus,
  "square-pen": SquarePen,
  "square-plus": SquarePlus,
  star: Star,
  "sticky-note": StickyNote,
  sun: Sun,
  table: Table,
  tags: Tags,
  terminal: Terminal,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  "toggle-right": ToggleRight,
  "trash-2": Trash2,
  "tree-pine": TreePine,
  "triangle-alert": TriangleAlert,
  type: Type,
  "undo-2": Undo2,
  unlink: Unlink,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  "user-lock": UserLock,
  "user-pen": UserPen,
  "user-round": UserRound,
  users: Users,
  variable: Variable,
  vault: Vault,
  video: Video,
  youtube: Video,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "wand-sparkles": WandSparkles,
  waypoints: Waypoints,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  "quick-connect": Flame,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
